version: '3.8'

services:
  backend:
    build:
      context: ./backend  
    ports:
      - "3000:3000"  
    networks:
      - mynetwork

  frontend:
    build:
      context: ./frontend  
    ports:
      - "8081:80"  
    depends_on:
      - backend  
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge


